// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokedex.Models;

namespace Pokedex.Migrations
{
    [DbContext(typeof(PokedexContext))]
    partial class PokedexContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Pokedex.PokedexCategoryEntry", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<bool?>("Acquired")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP)");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP)");

                    b.Property<bool>("Encountered")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("AccountId", "Category");

                    b.ToTable("PokedexCategoryEntry");
                });

            modelBuilder.Entity("Pokedex.PokedexEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CapturedShiny")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP)");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP)");

                    b.Property<bool>("EncounteredShiny")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EvolutionStonePieces")
                        .HasColumnType("int");

                    b.Property<int>("EvolutionStones")
                        .HasColumnType("int");

                    b.Property<int>("PokedexId")
                        .HasColumnType("int");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TimesCaptured")
                        .HasColumnType("int");

                    b.Property<int>("TimesEncountered")
                        .HasColumnType("int");

                    b.Property<int>("TimesLuckyReceived")
                        .HasColumnType("int");

                    b.Property<int>("TimesPurified")
                        .HasColumnType("int");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PokedexEntry");
                });

            modelBuilder.Entity("Pokedex.PokedexEnum", b =>
                {
                    b.Property<int>("EnumValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP)");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP)");

                    b.Property<string>("EnumName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("PokedexEntryId")
                        .HasColumnType("int");

                    b.Property<int?>("PokedexEntryId1")
                        .HasColumnType("int");

                    b.Property<int?>("PokedexEntryId2")
                        .HasColumnType("int");

                    b.Property<int?>("PokedexEntryId3")
                        .HasColumnType("int");

                    b.Property<int?>("PokedexEntryId4")
                        .HasColumnType("int");

                    b.Property<int?>("PokedexEntryId5")
                        .HasColumnType("int");

                    b.Property<int?>("PokedexEntryId6")
                        .HasColumnType("int");

                    b.Property<int?>("PokedexEntryId7")
                        .HasColumnType("int");

                    b.HasKey("EnumValue");

                    b.HasIndex("PokedexEntryId");

                    b.HasIndex("PokedexEntryId1");

                    b.HasIndex("PokedexEntryId2");

                    b.HasIndex("PokedexEntryId3");

                    b.HasIndex("PokedexEntryId4");

                    b.HasIndex("PokedexEntryId5");

                    b.HasIndex("PokedexEntryId6");

                    b.HasIndex("PokedexEntryId7");

                    b.ToTable("PokedexEnum");
                });

            modelBuilder.Entity("Pokedex.Snapshot", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP)");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP)");

                    b.HasKey("SnapshotId");

                    b.ToTable("Snapshot");
                });

            modelBuilder.Entity("PolygonStats.Plugins.Data.Pokemon", b =>
                {
                    b.Property<long?>("PokedexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("Attack")
                        .HasColumnType("bigint");

                    b.Property<long?>("BonusCandyCapture")
                        .HasColumnType("bigint");

                    b.Property<long?>("BonusStardustCapture")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuddyDistance")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuddyGroupNumber")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuddyMegaEnergy")
                        .HasColumnType("bigint");

                    b.Property<double?>("CaptureRate")
                        .HasColumnType("double");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP)");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP)");

                    b.Property<long?>("DefaultFormId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Defense")
                        .HasColumnType("bigint");

                    b.Property<long?>("Family")
                        .HasColumnType("bigint");

                    b.Property<double?>("FleeRate")
                        .HasColumnType("double");

                    b.Property<long?>("GenId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("GymDefenderEligible")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("Height")
                        .HasColumnType("double");

                    b.Property<bool?>("Legendary")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Little")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Mythic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PokemonName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("Stamina")
                        .HasColumnType("bigint");

                    b.Property<long?>("ThirdMoveCandy")
                        .HasColumnType("bigint");

                    b.Property<long?>("ThirdMoveStardust")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Tradable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Transferable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("UltraBeast")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Unreleased")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("Weight")
                        .HasColumnType("double");

                    b.HasKey("PokedexId");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("Pokedex.PokedexEnum", b =>
                {
                    b.HasOne("Pokedex.PokedexEntry", null)
                        .WithMany("CapturedCostumes")
                        .HasForeignKey("PokedexEntryId");

                    b.HasOne("Pokedex.PokedexEntry", null)
                        .WithMany("CapturedForms")
                        .HasForeignKey("PokedexEntryId1");

                    b.HasOne("Pokedex.PokedexEntry", null)
                        .WithMany("CapturedGenders")
                        .HasForeignKey("PokedexEntryId2");

                    b.HasOne("Pokedex.PokedexEntry", null)
                        .WithMany("CapturedShinyAlignments")
                        .HasForeignKey("PokedexEntryId3");

                    b.HasOne("Pokedex.PokedexEntry", null)
                        .WithMany("CapturedShinyForms")
                        .HasForeignKey("PokedexEntryId4");

                    b.HasOne("Pokedex.PokedexEntry", null)
                        .WithMany("EncounteredCostumes")
                        .HasForeignKey("PokedexEntryId5");

                    b.HasOne("Pokedex.PokedexEntry", null)
                        .WithMany("EncounteredForms")
                        .HasForeignKey("PokedexEntryId6");

                    b.HasOne("Pokedex.PokedexEntry", null)
                        .WithMany("EncounteredGenders")
                        .HasForeignKey("PokedexEntryId7");
                });

            modelBuilder.Entity("Pokedex.PokedexEntry", b =>
                {
                    b.Navigation("CapturedCostumes");

                    b.Navigation("CapturedForms");

                    b.Navigation("CapturedGenders");

                    b.Navigation("CapturedShinyAlignments");

                    b.Navigation("CapturedShinyForms");

                    b.Navigation("EncounteredCostumes");

                    b.Navigation("EncounteredForms");

                    b.Navigation("EncounteredGenders");
                });
#pragma warning restore 612, 618
        }
    }
}
